
<a href="https://githubtocolab.com/Astolfo2332/white_paper_LoRa/blob/main/math_exercises.ipynb" target="_parent\">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" > </a>


<div style="display: flex; align-items: center;">
    <div>
        <h2>Ejercicios evaluables</h2>
        <h2>Miguel López</h2>
        <h2>ID 1001014378</h2>
    </div>
    <img src="https://yt3.ggpht.com/-10IUL9wra6k/AAAAAAAAAAI/AAAAAAAAAAA/UOBLu1uYOOE/s900-c-k-no/photo.jpg" alt="Image description" width="200" style="margin-left: 20px;"/>
</div>

## Solución

### 1. a Implementa una función, determinante recursivo, que obtenga el determinante de una matriz cuadrada utilizando la definición recursiva de Laplace.

In [5]:
import  numpy as np

def determinante_recursivo(matriz):
    #Evaluar si la matriz es cuadrada
    if matriz.shape[0] != matriz.shape[1]:
        raise ValueError("La matriz no es cuadrada")
    if matriz.shape[0] == 1:
        return matriz[0,0]
    det = 0
    for i in range(matriz.shape[0]):
        #Tomamos los valores de la primera fila y los delimitamos con la columna i
        #Eliminando la primera fila y la columna i
        det += (-1)**i * matriz[0,i] * determinante_recursivo(np.delete(np.delete(matriz, 0, 0), i, 1))
    return det

test = [np.array([[1,2,3],[4,5,6],[7,8,9]]),
        np.array([[1,2,3],[4,5,6],[7,8,10]]),
        np.array([[1,2],[3,4]])]

for i in test:
    print(i)
    print("Determinante:", determinante_recursivo(i))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinante: 0
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
Determinante: -3
[[1 2]
 [3 4]]
Determinante: -2


### 1. b
Si A es una matriz cuadrada $n×n$ y triangular (superior o inferior, es decir, con entradas nulas por debajo o por encima de la diagonal, respectivamente), ¿existe alguna forma de calcular de forma directa y sencilla su determinante? Justifíquese la respuesta.

### Respuesta

 Nos ayudaremos del código anterior, pero en sí se da debido a que la multiplicación con sus pares superiores o inferiores van a ser 0, por ende solo quedaría multiplicar los elementos de la diagonal principal. Notes claro que si uno de estos elementos es 0 el determinante será 0. Pero se puede demostrar de la siguiente forma en un caso general de matriz triangular inferior:

$$
\begin{vmatrix}
a & b & c \\
0 & d & e \\
0 & 0 & f \\
\end{vmatrix}
= a \cdot
\begin{vmatrix}
d & e \\
0 & f \\
\end{vmatrix}
- b \cdot
\begin{vmatrix}
0 & e \\
0 & f \\
\end{vmatrix}
+ c \cdot
\begin{vmatrix}
0 & d \\
0 & 0 \\
\end{vmatrix}
$$

$$
= a \cdot (d \cdot f) - b \cdot 0 + c \cdot 0
$$

$$
= a \cdot d \cdot f
$$

Para una triangular superior funciona de la misma forma.

$$
\begin{vmatrix}
a & 0 & 0 \\
b & d & 0 \\
c & e & f \\
\end{vmatrix}
= a \cdot
\begin{vmatrix}
d & 0 \\
e & f \\
\end{vmatrix}
- 0 \cdot
\begin{vmatrix}
b & 0 \\
c & f \\
\end{vmatrix}
+ 0 \cdot
\begin{vmatrix}
b & d \\
c & e \\
\end{vmatrix}
$$

$$
= a \cdot (d \cdot f) -  0 +  0
$$

$$
= a \cdot d \cdot f
$$





In [8]:
# Usando la función determinante_recursivo

test = [np.array([[1,0,0],[2,3,0],[4,5,6]]),
        np.array([[1,2,3],[0,4,5],[0,0,6]]),
        np.array([[1,0,0],[2,3,0],[4,5,6]]),]

for i in test:
    print(i)
    print("Determinante:", determinante_recursivo(i))
    #np.prod multiplica los elementos de un array y np.diag obtiene la diagonal de una matriz
    print("Determinante multiplicando diagonal:", np.prod(np.diag(i)))

[[1 0 0]
 [2 3 0]
 [4 5 6]]
Determinante: 18
Determinante multiplicando diagonal: 18
[[1 2 3]
 [0 4 5]
 [0 0 6]]
Determinante: 24
Determinante multiplicando diagonal: 24
[[1 0 0]
 [2 3 0]
 [4 5 6]]
Determinante: 18
Determinante multiplicando diagonal: 18


### 1. c
Determínese de forma justificada cómo alteran el determinante de una
matriz $n × n$ las dos operaciones elementales siguientes:

- Intercambiar una fila (o columna) por otra fila (o columna).
- Sumar a una fila (o columna) otra fila (o columna) multiplicada por un escalar α.

### Respuesta

En el caso de intercamabiar una fila por otra, el determinante cambia de signo, esto se puede demostrar de la siguiente forma, supongamos una matrix $A$ y otra $A'$ que es la matriz $A$ con las filas $i$ y $j$ intercambiadas, entonces:
$$
A =
\begin{vmatrix}
a & b \\
c & d \\
\end{vmatrix}
= a \cdot d - b \cdot c
$$

Al realizar el cambio de fila:

$$
A' =
\begin{vmatrix}
c & d \\
a & b \\
\end{vmatrix}
= c \cdot b - d \cdot a
$$

Así si igualamos las dos expresiones anteriores:

$$
a \cdot d - b \cdot c = -(d \cdot a - c \cdot b)
$$

Por consiguiente se puede concluir que el determinante es:

$$
det(A) = -det(A')
$$


In [11]:
test = [np.array([[1,2],[3,4]]),
        np.array([[4,5],[6,7]])]

for i in test:
    print(i)
    print("Determinante:", determinante_recursivo(i))
    #Intercambiamos las filas
    print(i[::-1])
    print("Determinante con filas intercambiadas:", determinante_recursivo(i[::-1]))

[[1 2]
 [3 4]]
Determinante: -2
[[3 4]
 [1 2]]
Determinante con filas intercambiadas: 2
[[4 5]
 [6 7]]
Determinante: -2
[[6 7]
 [4 5]]
Determinante con filas intercambiadas: 2


En el caso de sumar a una fila otra fila multiplicada por un escalar $\alpha$, el determinante no se ve afectado, esto se puede demostrar de la siguiente forma, supongamos una matrix $A$ y otra $A'$ que es la matriz $A$ con la fila $i$ multiplicada por un escalar $\alpha$ y sumada a la fila $j$, entonces:
$$
A =
\begin{vmatrix}
a & b \\
c & d \\
\end{vmatrix}
= a \cdot d - b \cdot c
$$

Aplicando la transformación:

$$
A' =
\begin{vmatrix}
a & b \\
c + \alpha a & d + \alpha b \\
\end{vmatrix}
= a \cdot (d + \alpha b) - b \cdot (c + \alpha a)
= a \cdot d + a \cdot \alpha b - b \cdot c - b \cdot \alpha a
= a \cdot d - b \cdot c
$$

Por ende el determinante no se ve afectado.


In [13]:
test = [np.array([[1,2],[3,4]]),
        np.array([[4,5],[6,7]])]

for i in test:
    print(i)
    print("Determinante:", determinante_recursivo(i))
    #Multiplicamos la primera fila por 2 y la sumamos a la segunda
    i[1] = i[1] + 2*i[0]
    print(i)
    print("Determinante con filas sumadas:", determinante_recursivo(i))

[[1 2]
 [3 4]]
Determinante: -2
[[1 2]
 [5 8]]
Determinante con filas sumadas: -2
[[4 5]
 [6 7]]
Determinante: -2
[[ 4  5]
 [14 17]]
Determinante con filas sumadas: -2


### 1. d
Investiga sobre el método de eliminación de Gauss con pivoteo parcial e impleméntalo para escalonar una matriz (es decir, convertirla en una matriz triangular inferior) a partir de las operaciones elementales descritas en el apartado anterior.

In [14]:
def gauss_pivoteo_parcial(matriz):
    #Matriz aumentada
    matriz = matriz.astype(float)
    n = matriz.shape[0]
    for i in range(n):
        #Pivoteo parcial
        max_index = np.argmax(np.abs(matriz[i:,i])) + i
        matriz[[i,max_index]] = matriz[[max_index,i]]
        for j in range(i+1, n):
            #Dividimos la fila por el pivote
            matriz[j] = matriz[j] - matriz[i] * matriz[j,i] / matriz[i,i]
    return matriz

test = [np.array([[1,2,3],[4,5,6],[7,8,9]]),
        np.array([[1,2,3],[4,5,6],[7,8,10]]),
        np.array([[1,2],[3,4]])]

for i in test:
    print(i)
    print(gauss_pivoteo_parcial(i))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.77156117e-16]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]
[[1 2]
 [3 4]]
[[3.         4.        ]
 [0.         0.66666667]]
